#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#homepage:
#  path: /
#  controller: App\Controller\SecurityController::login

#homepage:
  #path: /
  #controller: App\Controller\SecurityController::login

home:
  path: /
  controller: App\Controller\SecurityController::sitemap

sitemap:
  path: /sitemap
  controller: App\Controller\SecurityController::sitemap

post_ledger:
  path: /post
  controller: App\Controller\PostController::index

login:
  path: /login
  controller: App\Controller\SecurityController::login

user:
  path: /user
  controller: App\Controller\UserController::index
